theme: jekyll-theme-minimal
title: Starlight Romero's Portfolio
logo: https://media-exp1.licdn.com/dms/image/C5603AQG8o0QY1BPTPA/profile-displayphoto-shrink_200_200/0/1607629509909?e=1625097600&v=beta&t=1H17XnYve1wffX4KkAioa_-rbxbvnJNaAbakZbmEL0o
